-- MySQL Script generated by MySQL Workbench
-- Mon Oct 30 18:35:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema easybuild
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema easybuild
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `easybuild` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `easybuild` ;

-- -----------------------------------------------------
-- Table `easybuild`.`carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easybuild`.`carrinho` (
  `id` INT NOT NULL,
  `DataCriacao` VARCHAR(45) NULL DEFAULT NULL,
  `Status` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `easybuild`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easybuild`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NULL DEFAULT NULL,
  `marca` VARCHAR(200) NULL DEFAULT NULL,
  `quantidade` INT NULL DEFAULT NULL,
  `validade` VARCHAR(45) NULL DEFAULT NULL,
  `em_estoque` TINYINT NULL DEFAULT NULL,
  `preco` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `easybuild`.`carrinhoitem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `easybuild`.`carrinhoitem` (
  `id` INT NOT NULL,
  `CarrinhoID` INT NULL DEFAULT NULL,
  `ProdutoID` INT NULL DEFAULT NULL,
  `Quantidade` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `CarrinhoID` (`CarrinhoID` ASC) VISIBLE,
  INDEX `ProdutoID` (`ProdutoID` ASC) VISIBLE,
  CONSTRAINT `carrinhoitem_ibfk_1`
    FOREIGN KEY (`CarrinhoID`)
    REFERENCES `easybuild`.`carrinho` (`id`),
  CONSTRAINT `carrinhoitem_ibfk_2`
    FOREIGN KEY (`ProdutoID`)
    REFERENCES `easybuild`.`produtos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
